---
- name: generate ironic json file
  hosts: all
  gather_facts: false
  tasks:
  - name: generate json file
    template:
      src: /home/bschmaus/ironic_hosts.j2
      dest: /home/bschmaus/ironic_hosts.json
      mode: '0644'
    delegate_to: localhost
    run_once: True
